import { Profile, Project, DesignWork, WritingPost } from "@/types/content";

export const profile: Profile = {
  id: "main",
  name: "Emmanuel Ajibade",
  title: "Tech Specialist & Software Developer",
  shortIntro: "Building robust software and crafting thoughtful visual experiences.",
  bio: "A developer with a passion for design, creating digital products that are both functional and beautiful.",
  skills: ["TypeScript", "React", "Node.js", "UI Design", "Tailwind CSS", "Next.js"],
  interests: ["Open Source", "UI/UX", "Creative Coding"],
  profileImage: {
    url: "https://placehold.co/400x400",
    provider: "external",
    width: 400,
    height: 400,
    altText: "Placeholder portrait",
  },
  location: "Lagos, Nigeria",
  phone: "+234 9067502619",
  socialLinks: [
    { platform: "GitHub", url: "https://github.com/example" },
    { platform: "LinkedIn", url: "https://linkedin.com/in/example" },
  ],
  contactEmail: "aduremmanuel123@gmail.com",
};

export const projects: Project[] = [
  {
    id: "1",
    title: "Collabe",
    slug: "collabe",
    shortDescription: "A collaboration platform for teams.",
    description: "Collabe is a project that explores real-time collaboration tools.",
    type: "Web App",
    role: "Full Stack Developer",
    technologies: ["Next.js", "Firebase", "Tailwind CSS"],
    projectStatus: "completed",
    visibility: "published",
    date: "2024-01-15",
    thumbnail: {
      url: "https://placehold.co/600x400",
      provider: "external",
      width: 600,
      height: 400,
      altText: "Collabe thumbnail",
    },
    features: ["Real-time chat", "Task management", "File sharing"],
    githubUrl: "https://github.com/example/collabe",
    liveUrl: "https://collabe.example.com",
    featured: true,
    order: 1,
    tags: ["collaboration", "real-time"],
    active: true,   // Added
  },
  {
    id: "2",
    title: "Cloud Backup",
    slug: "cloud-backup",
    shortDescription: "A backup tool for cloud storage.",
    description: "Cloud Backup is an experimental project for managing file backups.",
    type: "CLI Tool",
    role: "Developer",
    technologies: ["Node.js", "TypeScript"],
    projectStatus: "in-progress",
    visibility: "published",
    date: "2024-03-10",
    thumbnail: {
      url: "https://placehold.co/600x400",
      provider: "external",
      width: 600,
      height: 400,
      altText: "Cloud Backup thumbnail",
    },
    features: ["Automated backups", "Encryption"],
    githubUrl: undefined,
    liveUrl: undefined,
    featured: false,
    order: 2,
    tags: ["devtools", "automation"],
    active: true,   // Added
  },
  {
    id: "3",
    title: "Portfolio Website",
    slug: "portfolio-website",
    shortDescription: "This personal portfolio site.",
    description: "The website you are looking at right now, built with Next.js.",
    type: "Website",
    role: "Designer & Developer",
    technologies: ["Next.js", "React", "Tailwind CSS", "Motion"],
    projectStatus: "completed",
    visibility: "published",
    date: "2024-06-01",
    thumbnail: {
      url: "https://placehold.co/600x400",
      provider: "external",
      width: 600,
      height: 400,
      altText: "Portfolio website thumbnail",
    },
    features: ["Responsive design", "Animations"],
    githubUrl: "https://github.com/example/portfolio",
    liveUrl: "https://emmanuel.example.com",
    featured: true,
    order: 3,
    tags: ["portfolio", "design"],
    active: true,   // Added
  },
];

export const designWorks: DesignWork[] = [
  {
    id: "d1",
    title: "Poster Series",
    slug: "poster-series",
    category: "Posters",
    image: {
      url: "https://placehold.co/600x800",
      provider: "external",
      width: 600,
      height: 800,
      altText: "Poster series",
    },
    description: "A series of posters for a tech event.",
    featured: true,
    order: 1,
    date: "2024-04-20",
  },
  {
    id: "d2",
    title: "Brand Identity",
    slug: "brand-identity",
    category: "Branding",
    image: {
      url: "https://placehold.co/1200x600",
      provider: "external",
      width: 1200,
      height: 600,
      altText: "Brand identity design",
    },
    description: "Logo and brand guidelines for a startup.",
    featured: true,
    order: 2,
    date: "2024-05-15",
  },
  {
    id: "d3",
    title: "Social Media Kit",
    slug: "social-media-kit",
    category: "Social Media",
    image: {
      url: "https://placehold.co/800x800",
      provider: "external",
      width: 800,
      height: 800,
      altText: "Social media kit",
    },
    description: "Instagram templates for a brand.",
    featured: false,
    order: 3,
    date: "2024-07-01",
  },
  {
    id: "d4",
    title: "UI Design – Dashboard",
    slug: "ui-dashboard",
    category: "UI/UX",
    image: {
      url: "https://placehold.co/1200x800",
      provider: "external",
      width: 1200,
      height: 800,
      altText: "Dashboard UI design",
    },
    description: "Analytics dashboard interface design.",
    featured: true,
    order: 4,
    date: "2024-08-10",
  },
  {
    id: "d5",
    title: "Wide Banner",
    slug: "wide-banner",
    category: "Print",
    image: {
      url: "https://placehold.co/1600x400",
      provider: "external",
      width: 1600,
      height: 400,
      altText: "Wide banner design",
    },
    description: "Banner for a conference.",
    featured: false,
    order: 5,
    date: "2024-09-05",
  },
  {
    id: "d6",
    title: "Motion Graphics",
    slug: "motion-graphics",
    category: "Motion",
    image: {
      url: "https://placehold.co/800x600",
      provider: "external",
      width: 800,
      height: 600,
      altText: "Motion graphics still",
    },
    description: "Animated logo reveal.",
    featured: false,
    order: 6,
    date: "2024-10-12",
  },
];

export const writingPosts: WritingPost[] = [
  {
    id: "w1",
    title: "Learning Next.js: A Practical Guide",
    slug: "learning-nextjs",
    summary: "Notes on getting started with Next.js, from project setup to deployment.",
    body: `Next.js is a powerful framework for building React applications. In this article, I'll walk through the key concepts I learned when starting with Next.js.\n\n## Why Next.js?\nNext.js provides server-side rendering, static generation, and API routes out of the box. It simplifies the development process and improves performance.\n\n## Setting Up a Project\nYou can create a new Next.js project with:\n\n\`\`\`bash\nnpx create-next-app my-app\n\`\`\`\n\n## Key Features\n- **File-based routing**: Pages are automatically created based on the folder structure.\n- **Server Components**: By default, components are server-rendered, which is great for SEO.\n- **Image Optimization**: Next.js Image component optimizes images automatically.\n\n## Conclusion\nNext.js is a great choice for building modern web applications. Its simplicity and power make it a joy to work with.`,
    category: "Tutorial",
    tags: ["next.js", "react", "web development"],
    date: "2024-02-01",
    updatedAt: "2024-03-15",
    coverImage: {
      url: "https://placehold.co/1200x600",
      provider: "external",
      width: 1200,
      height: 600,
      altText: "Next.js cover image",
    },
    visibility: "published",
    author: "Emmanuel Ajibade",
  },
  {
    id: "w2",
    title: "Designing for Developers: Bridging the Gap",
    slug: "designing-for-developers",
    summary: "How to make designs that are practical for developers and still beautiful.",
    body: `As a developer with a design background, I often see a disconnect between design and development. In this post, I share my approach to creating designs that are both visually appealing and feasible to implement.\n\n## Understand the Developer's Constraints\nDevelopers have to work with performance, accessibility, and maintainability. A great design should consider these from the start.\n\n## Use a Design System\nA design system with tokens (colors, spacing, typography) makes it easier for developers to implement consistent designs.\n\n## Communicate with Developers\nCollaboration is key. Sharing design files, annotations, and prototypes helps avoid misunderstandings.\n\n## Conclusion\nDesign and development are not separate silos. When they work together, the result is a product that is both beautiful and functional.`,
    category: "Article",
    tags: ["design", "development", "UI/UX"],
    date: "2024-04-10",
    coverImage: {
      url: "https://placehold.co/1200x600",
      provider: "external",
      width: 1200,
      height: 600,
      altText: "Design cover image",
    },
    visibility: "published",
    author: "Emmanuel Ajibade",
  },
];